-- GENERATED by scripts/generate-matches-seed.mjs — do not edit by hand.
-- 1) Map our teams to football-data ids (idempotent).
update teams set external_id = '1060' where name = 'Bosnia & Herzegovina';
update teams set external_id = '1836' where name = 'Panama';
update teams set external_id = '1930' where name = 'Cape Verde';
update teams set external_id = '1934' where name = 'DR Congo';
update teams set external_id = '1935' where name = 'Ivory Coast';
update teams set external_id = '758' where name = 'Uruguay';
update teams set external_id = '759' where name = 'Germany';
update teams set external_id = '760' where name = 'Spain';
update teams set external_id = '761' where name = 'Paraguay';
update teams set external_id = '762' where name = 'Argentina';
update teams set external_id = '763' where name = 'Ghana';
update teams set external_id = '764' where name = 'Brazil';
update teams set external_id = '765' where name = 'Portugal';
update teams set external_id = '766' where name = 'Japan';
update teams set external_id = '769' where name = 'Mexico';
update teams set external_id = '770' where name = 'England';
update teams set external_id = '771' where name = 'USA';
update teams set external_id = '772' where name = 'South Korea';
update teams set external_id = '773' where name = 'France';
update teams set external_id = '774' where name = 'South Africa';
update teams set external_id = '778' where name = 'Algeria';
update teams set external_id = '779' where name = 'Australia';
update teams set external_id = '783' where name = 'New Zealand';
update teams set external_id = '788' where name = 'Switzerland';
update teams set external_id = '791' where name = 'Ecuador';
update teams set external_id = '792' where name = 'Sweden';
update teams set external_id = '798' where name = 'Czech Republic';
update teams set external_id = '799' where name = 'Croatia';
update teams set external_id = '801' where name = 'Saudi Arabia';
update teams set external_id = '802' where name = 'Tunisia';
update teams set external_id = '803' where name = 'Turkey';
update teams set external_id = '8030' where name = 'Qatar';
update teams set external_id = '804' where name = 'Senegal';
update teams set external_id = '8049' where name = 'Jordan';
update teams set external_id = '805' where name = 'Belgium';
update teams set external_id = '8062' where name = 'Iraq';
update teams set external_id = '8070' where name = 'Uzbekistan';
update teams set external_id = '815' where name = 'Morocco';
update teams set external_id = '816' where name = 'Austria';
update teams set external_id = '818' where name = 'Colombia';
update teams set external_id = '825' where name = 'Egypt';
update teams set external_id = '828' where name = 'Canada';
update teams set external_id = '836' where name = 'Haiti';
update teams set external_id = '840' where name = 'Iran';
update teams set external_id = '8601' where name = 'Netherlands';
update teams set external_id = '8872' where name = 'Norway';
update teams set external_id = '8873' where name = 'Scotland';
update teams set external_id = '9460' where name = 'Curaçao';

-- 2) Seed the 104 fixtures. Knockout fixtures have null teams until rounds resolve.
insert into matches (external_id, stage, group_letter, home_team_id, away_team_id, kickoff_at, status) values
  ('537327', 'group', 'A', (select id from teams where external_id = '769'), (select id from teams where external_id = '774'), '2026-06-11T19:00:00Z', 'scheduled'),
  ('537328', 'group', 'A', (select id from teams where external_id = '772'), (select id from teams where external_id = '798'), '2026-06-12T02:00:00Z', 'scheduled'),
  ('537333', 'group', 'B', (select id from teams where external_id = '828'), (select id from teams where external_id = '1060'), '2026-06-12T19:00:00Z', 'scheduled'),
  ('537345', 'group', 'D', (select id from teams where external_id = '771'), (select id from teams where external_id = '761'), '2026-06-13T01:00:00Z', 'scheduled'),
  ('537334', 'group', 'B', (select id from teams where external_id = '8030'), (select id from teams where external_id = '788'), '2026-06-13T19:00:00Z', 'scheduled'),
  ('537339', 'group', 'C', (select id from teams where external_id = '764'), (select id from teams where external_id = '815'), '2026-06-13T22:00:00Z', 'scheduled'),
  ('537340', 'group', 'C', (select id from teams where external_id = '836'), (select id from teams where external_id = '8873'), '2026-06-14T01:00:00Z', 'scheduled'),
  ('537346', 'group', 'D', (select id from teams where external_id = '779'), (select id from teams where external_id = '803'), '2026-06-14T04:00:00Z', 'scheduled'),
  ('537351', 'group', 'E', (select id from teams where external_id = '759'), (select id from teams where external_id = '9460'), '2026-06-14T17:00:00Z', 'scheduled'),
  ('537357', 'group', 'F', (select id from teams where external_id = '8601'), (select id from teams where external_id = '766'), '2026-06-14T20:00:00Z', 'scheduled'),
  ('537352', 'group', 'E', (select id from teams where external_id = '1935'), (select id from teams where external_id = '791'), '2026-06-14T23:00:00Z', 'scheduled'),
  ('537358', 'group', 'F', (select id from teams where external_id = '792'), (select id from teams where external_id = '802'), '2026-06-15T02:00:00Z', 'scheduled'),
  ('537369', 'group', 'H', (select id from teams where external_id = '760'), (select id from teams where external_id = '1930'), '2026-06-15T16:00:00Z', 'scheduled'),
  ('537363', 'group', 'G', (select id from teams where external_id = '805'), (select id from teams where external_id = '825'), '2026-06-15T19:00:00Z', 'scheduled'),
  ('537370', 'group', 'H', (select id from teams where external_id = '801'), (select id from teams where external_id = '758'), '2026-06-15T22:00:00Z', 'scheduled'),
  ('537364', 'group', 'G', (select id from teams where external_id = '840'), (select id from teams where external_id = '783'), '2026-06-16T01:00:00Z', 'scheduled'),
  ('537391', 'group', 'I', (select id from teams where external_id = '773'), (select id from teams where external_id = '804'), '2026-06-16T19:00:00Z', 'scheduled'),
  ('537392', 'group', 'I', (select id from teams where external_id = '8062'), (select id from teams where external_id = '8872'), '2026-06-16T22:00:00Z', 'scheduled'),
  ('537397', 'group', 'J', (select id from teams where external_id = '762'), (select id from teams where external_id = '778'), '2026-06-17T01:00:00Z', 'scheduled'),
  ('537398', 'group', 'J', (select id from teams where external_id = '816'), (select id from teams where external_id = '8049'), '2026-06-17T04:00:00Z', 'scheduled'),
  ('537403', 'group', 'K', (select id from teams where external_id = '765'), (select id from teams where external_id = '1934'), '2026-06-17T17:00:00Z', 'scheduled'),
  ('537409', 'group', 'L', (select id from teams where external_id = '770'), (select id from teams where external_id = '799'), '2026-06-17T20:00:00Z', 'scheduled'),
  ('537410', 'group', 'L', (select id from teams where external_id = '763'), (select id from teams where external_id = '1836'), '2026-06-17T23:00:00Z', 'scheduled'),
  ('537404', 'group', 'K', (select id from teams where external_id = '8070'), (select id from teams where external_id = '818'), '2026-06-18T02:00:00Z', 'scheduled'),
  ('537329', 'group', 'A', (select id from teams where external_id = '798'), (select id from teams where external_id = '774'), '2026-06-18T16:00:00Z', 'scheduled'),
  ('537335', 'group', 'B', (select id from teams where external_id = '788'), (select id from teams where external_id = '1060'), '2026-06-18T19:00:00Z', 'scheduled'),
  ('537336', 'group', 'B', (select id from teams where external_id = '828'), (select id from teams where external_id = '8030'), '2026-06-18T22:00:00Z', 'scheduled'),
  ('537330', 'group', 'A', (select id from teams where external_id = '769'), (select id from teams where external_id = '772'), '2026-06-19T01:00:00Z', 'scheduled'),
  ('537348', 'group', 'D', (select id from teams where external_id = '771'), (select id from teams where external_id = '779'), '2026-06-19T19:00:00Z', 'scheduled'),
  ('537342', 'group', 'C', (select id from teams where external_id = '8873'), (select id from teams where external_id = '815'), '2026-06-19T22:00:00Z', 'scheduled'),
  ('537341', 'group', 'C', (select id from teams where external_id = '764'), (select id from teams where external_id = '836'), '2026-06-20T00:30:00Z', 'scheduled'),
  ('537347', 'group', 'D', (select id from teams where external_id = '803'), (select id from teams where external_id = '761'), '2026-06-20T03:00:00Z', 'scheduled'),
  ('537359', 'group', 'F', (select id from teams where external_id = '8601'), (select id from teams where external_id = '792'), '2026-06-20T17:00:00Z', 'scheduled'),
  ('537353', 'group', 'E', (select id from teams where external_id = '759'), (select id from teams where external_id = '1935'), '2026-06-20T20:00:00Z', 'scheduled'),
  ('537354', 'group', 'E', (select id from teams where external_id = '791'), (select id from teams where external_id = '9460'), '2026-06-21T00:00:00Z', 'scheduled'),
  ('537360', 'group', 'F', (select id from teams where external_id = '802'), (select id from teams where external_id = '766'), '2026-06-21T04:00:00Z', 'scheduled'),
  ('537371', 'group', 'H', (select id from teams where external_id = '760'), (select id from teams where external_id = '801'), '2026-06-21T16:00:00Z', 'scheduled'),
  ('537365', 'group', 'G', (select id from teams where external_id = '805'), (select id from teams where external_id = '840'), '2026-06-21T19:00:00Z', 'scheduled'),
  ('537372', 'group', 'H', (select id from teams where external_id = '758'), (select id from teams where external_id = '1930'), '2026-06-21T22:00:00Z', 'scheduled'),
  ('537366', 'group', 'G', (select id from teams where external_id = '783'), (select id from teams where external_id = '825'), '2026-06-22T01:00:00Z', 'scheduled'),
  ('537399', 'group', 'J', (select id from teams where external_id = '762'), (select id from teams where external_id = '816'), '2026-06-22T17:00:00Z', 'scheduled'),
  ('537393', 'group', 'I', (select id from teams where external_id = '773'), (select id from teams where external_id = '8062'), '2026-06-22T21:00:00Z', 'scheduled'),
  ('537394', 'group', 'I', (select id from teams where external_id = '8872'), (select id from teams where external_id = '804'), '2026-06-23T00:00:00Z', 'scheduled'),
  ('537400', 'group', 'J', (select id from teams where external_id = '8049'), (select id from teams where external_id = '778'), '2026-06-23T03:00:00Z', 'scheduled'),
  ('537405', 'group', 'K', (select id from teams where external_id = '765'), (select id from teams where external_id = '8070'), '2026-06-23T17:00:00Z', 'scheduled'),
  ('537411', 'group', 'L', (select id from teams where external_id = '770'), (select id from teams where external_id = '763'), '2026-06-23T20:00:00Z', 'scheduled'),
  ('537412', 'group', 'L', (select id from teams where external_id = '1836'), (select id from teams where external_id = '799'), '2026-06-23T23:00:00Z', 'scheduled'),
  ('537406', 'group', 'K', (select id from teams where external_id = '818'), (select id from teams where external_id = '1934'), '2026-06-24T02:00:00Z', 'scheduled'),
  ('537337', 'group', 'B', (select id from teams where external_id = '788'), (select id from teams where external_id = '828'), '2026-06-24T19:00:00Z', 'scheduled'),
  ('537338', 'group', 'B', (select id from teams where external_id = '1060'), (select id from teams where external_id = '8030'), '2026-06-24T19:00:00Z', 'scheduled'),
  ('537344', 'group', 'C', (select id from teams where external_id = '815'), (select id from teams where external_id = '836'), '2026-06-24T22:00:00Z', 'scheduled'),
  ('537343', 'group', 'C', (select id from teams where external_id = '8873'), (select id from teams where external_id = '764'), '2026-06-24T22:00:00Z', 'scheduled'),
  ('537331', 'group', 'A', (select id from teams where external_id = '798'), (select id from teams where external_id = '769'), '2026-06-25T01:00:00Z', 'scheduled'),
  ('537332', 'group', 'A', (select id from teams where external_id = '774'), (select id from teams where external_id = '772'), '2026-06-25T01:00:00Z', 'scheduled'),
  ('537355', 'group', 'E', (select id from teams where external_id = '791'), (select id from teams where external_id = '759'), '2026-06-25T20:00:00Z', 'scheduled'),
  ('537356', 'group', 'E', (select id from teams where external_id = '9460'), (select id from teams where external_id = '1935'), '2026-06-25T20:00:00Z', 'scheduled'),
  ('537361', 'group', 'F', (select id from teams where external_id = '802'), (select id from teams where external_id = '8601'), '2026-06-25T23:00:00Z', 'scheduled'),
  ('537362', 'group', 'F', (select id from teams where external_id = '766'), (select id from teams where external_id = '792'), '2026-06-25T23:00:00Z', 'scheduled'),
  ('537349', 'group', 'D', (select id from teams where external_id = '803'), (select id from teams where external_id = '771'), '2026-06-26T02:00:00Z', 'scheduled'),
  ('537350', 'group', 'D', (select id from teams where external_id = '761'), (select id from teams where external_id = '779'), '2026-06-26T02:00:00Z', 'scheduled'),
  ('537395', 'group', 'I', (select id from teams where external_id = '8872'), (select id from teams where external_id = '773'), '2026-06-26T19:00:00Z', 'scheduled'),
  ('537396', 'group', 'I', (select id from teams where external_id = '804'), (select id from teams where external_id = '8062'), '2026-06-26T19:00:00Z', 'scheduled'),
  ('537373', 'group', 'H', (select id from teams where external_id = '758'), (select id from teams where external_id = '760'), '2026-06-27T00:00:00Z', 'scheduled'),
  ('537374', 'group', 'H', (select id from teams where external_id = '1930'), (select id from teams where external_id = '801'), '2026-06-27T00:00:00Z', 'scheduled'),
  ('537367', 'group', 'G', (select id from teams where external_id = '783'), (select id from teams where external_id = '805'), '2026-06-27T03:00:00Z', 'scheduled'),
  ('537368', 'group', 'G', (select id from teams where external_id = '825'), (select id from teams where external_id = '840'), '2026-06-27T03:00:00Z', 'scheduled'),
  ('537413', 'group', 'L', (select id from teams where external_id = '1836'), (select id from teams where external_id = '770'), '2026-06-27T21:00:00Z', 'scheduled'),
  ('537414', 'group', 'L', (select id from teams where external_id = '799'), (select id from teams where external_id = '763'), '2026-06-27T21:00:00Z', 'scheduled'),
  ('537407', 'group', 'K', (select id from teams where external_id = '818'), (select id from teams where external_id = '765'), '2026-06-27T23:30:00Z', 'scheduled'),
  ('537408', 'group', 'K', (select id from teams where external_id = '1934'), (select id from teams where external_id = '8070'), '2026-06-27T23:30:00Z', 'scheduled'),
  ('537401', 'group', 'J', (select id from teams where external_id = '8049'), (select id from teams where external_id = '762'), '2026-06-28T02:00:00Z', 'scheduled'),
  ('537402', 'group', 'J', (select id from teams where external_id = '778'), (select id from teams where external_id = '816'), '2026-06-28T02:00:00Z', 'scheduled'),
  ('537417', 'r32', null, null, null, '2026-06-28T19:00:00Z', 'scheduled'),
  ('537423', 'r32', null, null, null, '2026-06-29T17:00:00Z', 'scheduled'),
  ('537415', 'r32', null, null, null, '2026-06-29T20:30:00Z', 'scheduled'),
  ('537418', 'r32', null, null, null, '2026-06-30T01:00:00Z', 'scheduled'),
  ('537424', 'r32', null, null, null, '2026-06-30T17:00:00Z', 'scheduled'),
  ('537416', 'r32', null, null, null, '2026-06-30T21:00:00Z', 'scheduled'),
  ('537425', 'r32', null, null, null, '2026-07-01T01:00:00Z', 'scheduled'),
  ('537426', 'r32', null, null, null, '2026-07-01T16:00:00Z', 'scheduled'),
  ('537422', 'r32', null, null, null, '2026-07-01T20:00:00Z', 'scheduled'),
  ('537421', 'r32', null, null, null, '2026-07-02T00:00:00Z', 'scheduled'),
  ('537420', 'r32', null, null, null, '2026-07-02T19:00:00Z', 'scheduled'),
  ('537419', 'r32', null, null, null, '2026-07-02T23:00:00Z', 'scheduled'),
  ('537429', 'r32', null, null, null, '2026-07-03T03:00:00Z', 'scheduled'),
  ('537428', 'r32', null, null, null, '2026-07-03T18:00:00Z', 'scheduled'),
  ('537427', 'r32', null, null, null, '2026-07-03T22:00:00Z', 'scheduled'),
  ('537430', 'r32', null, null, null, '2026-07-04T01:30:00Z', 'scheduled'),
  ('537376', 'r16', null, null, null, '2026-07-04T17:00:00Z', 'scheduled'),
  ('537375', 'r16', null, null, null, '2026-07-04T21:00:00Z', 'scheduled'),
  ('537377', 'r16', null, null, null, '2026-07-05T20:00:00Z', 'scheduled'),
  ('537378', 'r16', null, null, null, '2026-07-06T00:00:00Z', 'scheduled'),
  ('537379', 'r16', null, null, null, '2026-07-06T19:00:00Z', 'scheduled'),
  ('537380', 'r16', null, null, null, '2026-07-07T00:00:00Z', 'scheduled'),
  ('537381', 'r16', null, null, null, '2026-07-07T16:00:00Z', 'scheduled'),
  ('537382', 'r16', null, null, null, '2026-07-07T20:00:00Z', 'scheduled'),
  ('537383', 'qf', null, null, null, '2026-07-09T20:00:00Z', 'scheduled'),
  ('537384', 'qf', null, null, null, '2026-07-10T19:00:00Z', 'scheduled'),
  ('537385', 'qf', null, null, null, '2026-07-11T21:00:00Z', 'scheduled'),
  ('537386', 'qf', null, null, null, '2026-07-12T01:00:00Z', 'scheduled'),
  ('537387', 'sf', null, null, null, '2026-07-14T19:00:00Z', 'scheduled'),
  ('537388', 'sf', null, null, null, '2026-07-15T19:00:00Z', 'scheduled'),
  ('537389', 'third_place', null, null, null, '2026-07-18T21:00:00Z', 'scheduled'),
  ('537390', 'final', null, null, null, '2026-07-19T19:00:00Z', 'scheduled')
on conflict (external_id) do update set
  stage = excluded.stage,
  group_letter = excluded.group_letter,
  home_team_id = coalesce(excluded.home_team_id, matches.home_team_id),
  away_team_id = coalesce(excluded.away_team_id, matches.away_team_id),
  kickoff_at = excluded.kickoff_at;
